-- ── 1. guide_likes ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.guide_likes (
  id          bigint generated by default as identity not null,
  guide_id    uuid not null,
  user_id     uuid not null,
  reaction    text not null, -- 'like' | 'dislike'
  created_at  timestamp with time zone not null default now(),

  constraint guide_likes_pkey primary key (id),
  constraint guide_likes_unique unique (guide_id, user_id),
  constraint guide_likes_guide_fkey foreign key (guide_id)
    references guides (guide_id) on delete cascade,
  constraint guide_likes_user_fkey foreign key (user_id)
    references "Users" (user_id) on delete cascade,
  constraint guide_likes_reaction_check check (
    reaction = any (array['like'::text, 'dislike'::text])
  )
);

-- RLS for guide_likes
ALTER TABLE public.guide_likes ENABLE ROW LEVEL SECURITY;

-- Anyone can read likes (for counts)
DROP POLICY IF EXISTS "public_select_guide_likes" ON public.guide_likes;
CREATE POLICY "public_select_guide_likes"
  ON public.guide_likes FOR SELECT
  TO anon, authenticated
  USING (true);

-- Authenticated users can insert their own reactions
DROP POLICY IF EXISTS "user_insert_guide_likes" ON public.guide_likes;
CREATE POLICY "user_insert_guide_likes"
  ON public.guide_likes FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- Authenticated users can update their own reactions
DROP POLICY IF EXISTS "user_update_guide_likes" ON public.guide_likes;
CREATE POLICY "user_update_guide_likes"
  ON public.guide_likes FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Authenticated users can delete (un-react) their own reactions
DROP POLICY IF EXISTS "user_delete_guide_likes" ON public.guide_likes;
CREATE POLICY "user_delete_guide_likes"
  ON public.guide_likes FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- ── 2. admin_guide_history_hidden flag ─────────────────────────
-- Soft-delete for admin History tab only.
-- Adds a column to guide_rejections / guides to track admin-hidden state.
-- We use a separate small table to avoid altering the guides schema.

CREATE TABLE IF NOT EXISTS public.admin_hidden_guides (
  guide_id    uuid not null,
  hidden_by   text not null,
  hidden_at   timestamp with time zone not null default now(),

  constraint admin_hidden_guides_pkey primary key (guide_id)
);

ALTER TABLE public.admin_hidden_guides ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admin_manage_hidden_guides" ON public.admin_hidden_guides;
CREATE POLICY "admin_manage_hidden_guides"
  ON public.admin_hidden_guides
  FOR ALL
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);
